database_name = "siddharth_db" 
database_user = "sid_user" 
shared_credentials_file = "~/ .aws/credentials"
region        = "ap-south-1"  
ami           = "ami-0108d6a82a783b352"  
key_name =  "siddharth-hu" 
instance_type = "t2.micro" 